#!/usr/bin/env python3
"""Upload a generated repository PDF to Google Drive using OAuth credentials."""

from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload

DRIVE_SCOPE = "https://www.googleapis.com/auth/drive"
TOKEN_URI = "https://oauth2.googleapis.com/token"
FOLDER_MIME_TYPE = "application/vnd.google-apps.folder"


def required_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Required environment variable {name} is not set.")
    return value


def append_line(path: str | None, line: str) -> None:
    if path:
        with Path(path).open("a", encoding="utf-8") as handle:
            handle.write(f"{line}\n")


def repository_slug() -> str:
    repository = os.environ.get("GITHUB_REPOSITORY", "repository").split("/")[-1]
    slug = re.sub(r"[^a-z0-9]+", "-", repository.lower()).strip("-")
    return slug or "repository"


def main() -> int:
    source = Path(sys.argv[1] if len(sys.argv) > 1 else "dist/repository-docs.pdf")
    if not source.is_file():
        raise FileNotFoundError(f"PDF not found: {source}")

    credentials = Credentials(
        token=None,
        refresh_token=required_env("GOOGLE_DRIVE_REFRESH_TOKEN"),
        token_uri=TOKEN_URI,
        client_id=required_env("GOOGLE_DRIVE_CLIENT_ID"),
        client_secret=required_env("GOOGLE_DRIVE_CLIENT_SECRET"),
        scopes=[DRIVE_SCOPE],
    )
    folder_id = required_env("GOOGLE_DRIVE_FOLDER_ID")
    credentials.refresh(Request())
    drive = build("drive", "v3", credentials=credentials, cache_discovery=False)
    folder = drive.files().get(
        fileId=folder_id,
        fields="id,name,mimeType,capabilities(canAddChildren)",
        supportsAllDrives=True,
    ).execute()
    if folder.get("mimeType") != FOLDER_MIME_TYPE:
        raise RuntimeError("GOOGLE_DRIVE_FOLDER_ID does not identify a folder.")
    if not folder.get("capabilities", {}).get("canAddChildren", False):
        raise PermissionError("The authorized Google account cannot add files to the target folder.")

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    short_sha = os.environ.get("GITHUB_SHA", "").strip()[:7]
    default_name = f"{repository_slug()}-docs-{timestamp}" + (f"-{short_sha}" if short_sha else "") + ".pdf"
    remote_name = os.environ.get("GOOGLE_DRIVE_FILE_NAME", "").strip() or default_name

    repository = os.environ.get("GITHUB_REPOSITORY", "").strip()
    run_id = os.environ.get("GITHUB_RUN_ID", "").strip()
    description = ["Generated by the Agentic Repo Template (ART) CodeBinder PDF workflow."]
    if repository and run_id:
        description.append(f"GitHub run: {repository} #{run_id}.")
    if short_sha:
        description.append(f"Commit: {short_sha}.")

    media = MediaFileUpload(str(source), mimetype="application/pdf", resumable=True, chunksize=5 * 1024 * 1024)
    request = drive.files().create(
        body={"name": remote_name, "parents": [folder_id], "description": " ".join(description)},
        media_body=media,
        fields="id,name,webViewLink,createdTime,size",
        supportsAllDrives=True,
    )
    result = None
    while result is None:
        status, result = request.next_chunk()
        if status:
            print(f"Google Drive upload progress: {status.progress() * 100:.0f}%")

    file_id = result["id"]
    file_name = result["name"]
    file_url = result.get("webViewLink") or f"https://drive.google.com/file/d/{file_id}/view"
    print(f"Uploaded {file_name} to Google Drive folder {folder['name']}: {file_url}")
    append_line(os.environ.get("GITHUB_OUTPUT"), f"file_id={file_id}")
    append_line(os.environ.get("GITHUB_OUTPUT"), f"file_name={file_name}")
    append_line(os.environ.get("GITHUB_OUTPUT"), f"file_url={file_url}")
    append_line(os.environ.get("GITHUB_STEP_SUMMARY"), f"Google Drive: [{file_name}]({file_url})")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (FileNotFoundError, PermissionError, RuntimeError, HttpError) as exc:
        print(f"Google Drive upload failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
